/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts;

import static java.lang.Math.toIntExact;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kambing.ui.ac.id
 */
public class rental extends javax.swing.JFrame {

    /**
     * Creates new form rental
     */
    
    public rental() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tNama = new javax.swing.JTextField();
        tStruk = new javax.swing.JTextField();
        tAlamat = new javax.swing.JTextField();
        tPol = new javax.swing.JTextField();
        tLama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tPinjam = new com.toedter.calendar.JDateChooser();
        tKembali = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        tHarga = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRental = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 255, 0));
        jPanel1.setForeground(new java.awt.Color(51, 255, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        jLabel1.setText("RENTAL MOTOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(456, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 1000, 80);

        jPanel2.setBackground(new java.awt.Color(0, 255, 51));
        jPanel2.setLayout(null);

        tNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaActionPerformed(evt);
            }
        });
        jPanel2.add(tNama);
        tNama.setBounds(87, 38, 134, 32);

        tStruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tStrukActionPerformed(evt);
            }
        });
        jPanel2.add(tStruk);
        tStruk.setBounds(87, 164, 134, 32);

        tAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAlamatActionPerformed(evt);
            }
        });
        jPanel2.add(tAlamat);
        tAlamat.setBounds(87, 101, 134, 32);
        jPanel2.add(tPol);
        tPol.setBounds(87, 225, 134, 32);
        jPanel2.add(tLama);
        tLama.setBounds(87, 416, 134, 32);

        jLabel6.setText("Nama Peminjam");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(61, 9, 100, 20);

        jLabel7.setText("Alamat Peminjam");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(61, 75, 100, 20);

        jLabel8.setText("No. Struk");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(61, 139, 80, 20);

        jLabel9.setText("No. Polisi");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(61, 200, 70, 20);

        jLabel10.setText("Tanggal Pinjam");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(61, 263, 90, 20);

        jLabel11.setText("Tanggal Kembali");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(61, 321, 110, 30);

        jLabel12.setText("Lama Pinjam");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(61, 380, 90, 30);
        jPanel2.add(tPinjam);
        tPinjam.setBounds(90, 295, 131, 25);
        jPanel2.add(tKembali);
        tKembali.setBounds(90, 353, 131, 25);

        jLabel13.setText("Harga");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(61, 465, 60, 20);
        jPanel2.add(tHarga);
        tHarga.setBounds(87, 491, 134, 32);

        jButton1.setText("Hitung hari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(270, 10, 110, 23);

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(403, 9, 90, 23);

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(519, 9, 80, 23);

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(613, 10, 100, 23);

        jButton6.setText("Print");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(740, 10, 100, 23);

        tbRental.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "Alamat", "No. Struk", "No. Polisi", "Tanggal Pinjam", "Tanggal Kembali", "Lama Pinjam", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tbRental);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(240, 40, 740, 480);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 100, 1000, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaActionPerformed

    private void tAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tAlamatActionPerformed

    private void tStrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tStrukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tStrukActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String pinjam = dateFormat.format(tPinjam.getDate());
        String kembali = dateFormat.format(tKembali.getDate());
        
       
        if("".equals(tNama.getText()) || "".equals(tAlamat.getText()) || "".equals(tStruk.getText()) || pinjam.equals("") || kembali.equals("") || "".equals(tPol.getText()) ||  "".equals(tHarga.getText())   ){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {

            String SQL = "INSERT INTO data VALUES ('"+tNama.getText()+"','"+tAlamat.getText()+"','"+tStruk.getText()+"','"+"','"+"','"+tPol.getText()+"','"+pinjam+"','"+kembali+"','"+tHarga.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if(status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     Date Pinjam = tPinjam.getDate();
        Date Kembali = tKembali.getDate();
        long startTime = Pinjam.getTime();
        long endTime = Kembali.getTime();
        
        long sewaTime = endTime - startTime;
        long bedaHari = sewaTime/(1000 * 60 * 60 * 24);
        DateFormat dateFormat = DateFormat.getDateInstance();
        
        tLama.setText(" "+bedaHari+" hari");
        
        int lama = toIntExact(bedaHari);
        int total = lama * 20000;
        String harga = Integer.toString(total);
        
        tHarga.setText(harga);                                      

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        tNama.setText("");
        tAlamat.setText("");
        tStruk.setText("");
        tPol.setText("");
        tPinjam.setDate(null);
        tKembali.setDate(null);
        tHarga.setText("");
        tLama.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int baris = tbRental.getSelectedRow();
        int confirm = JOptionPane.showConfirmDialog(null,"Anda yakin ingin menghapus data?","Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm == 0){
            if(baris != -1){
                String struk = tbRental.getValueAt(baris, 2).toString();
                String SQL = "DELETE FROM db_uts WHERE struk='"+struk+"'";
                int status = KoneksiDB.execute(SQL);
                
                if(status == 1){
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
                }
            } else {
               JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Biodata Siswa SMK Telkom Malang");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}   ");
        try{
            tbRental.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rental().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tAlamat;
    private javax.swing.JTextField tHarga;
    private com.toedter.calendar.JDateChooser tKembali;
    private javax.swing.JTextField tLama;
    private javax.swing.JTextField tNama;
    private com.toedter.calendar.JDateChooser tPinjam;
    private javax.swing.JTextField tPol;
    private javax.swing.JTextField tStruk;
    private javax.swing.JTable tbRental;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"nama","alamat","struk","nopol","tgl_pinjam","tgl_kembali","lama_pinjam","harga"};
       DefaultTableModel dtm = new DefaultTableModel(null, kolom);
       String SQL = "SELECT * FROM db_uts";
       ResultSet rs = KoneksiDB.executeQuery(SQL);
       try{
           while(rs.next()){
               String Nama = rs.getString(1);
               String Alamat = rs.getString(2);
               String STRUK = rs.getString(3);
               String Pol = rs.getString(4);
               String Pinjam = rs.getString(5);
               String Kembali = rs.getString(6);
               String Lama = rs.getString(7);
               String Harga = rs.getString(8);
               String data [] = {Nama,Alamat,STRUK,Pol,Pinjam,Kembali,Lama,Harga};
               dtm.addRow(data);
           }   
        }catch(SQLException ex){
            Logger.getLogger(rental.class.getName()).log(Level.SEVERE, null, ex);
        }
       tbRental.setModel(dtm);

    }

}